/// AppStrings provides localized string resources for Gujarati ('gu'),
/// Hindi ('hi'), and English ('en').
class AppStrings {
  AppStrings._();

  static const String appName = 'વાલ્મીકિ રામાયણ';

  static final Map<String, Map<String, String>> _strings = {
    'gu': {
      'app_title': 'વાલ્મીકિ રામાયણ',
      'app_subtitle': 'શ્રી રામના પાવન જીવન અને આદર્શોની યાત્રા',
      'hero_subtitle': 'રામાયણના પવિત્ર જ્ઞાન અને પાત્રોની સુંદર યાત્રા',
      'select_language_title': 'વાલ્મીકિ રામાયણ',
      'select_language_subtitle': 'શ્રી રામના પાવન જીવન અને આદર્શોની યાત્રા',
      'choose_language_prompt': 'તમારી ભાષા પસંદ કરો',
      'continue_btn': 'આગળ વધો',
      'nav_home': 'મુખ્ય પૃષ્ઠ',
      'nav_categories': 'શ્રેણીઓ',
      'nav_favorites': 'પસંદગી',
      'nav_settings': 'સેટિંગ્સ',
      'main_categories_header': 'મુખ્ય શ્રેણીઓ',
      'continue_reading': 'વાંચન ચાલુ રાખો',
      'recently_viewed': 'તાજેતરમાં જોયેલું',
      'favorites_preview': 'તમારી પસંદગીના પાત્રો',
      'search_placeholder': 'શોધો (શೀರ್ષક અથવા વર્ણન)...',
      'category_search_placeholder': 'શ્રેણીમાં શોધો...',
      'no_results_title': 'કોઈ પરિણામ મળ્યા નથી',
      'no_results_desc': 'તમારા શોધ શબ્દ સાથે મેળ ખાતું કંઈ મળ્યું નથી.',
      'no_favorites_title': 'કોઈ પસંદગી ઉમેરી નથી',
      'no_favorites_desc': 'તમે હજી સુધી કોઈ શ્લોક કે પાત્ર પસંદગીમાં ઉમેર્યું નથી.',
      'font_small': 'નાના',
      'font_medium': 'મધ્યમ',
      'font_large': 'મોટા',
      'font_extra_large': 'વિશાળ',
      'settings_title': 'સેટિંગ્સ',
      'settings_header_subtitle': 'તમારી ભક્તિમય વાંચન પસંદગીઓ ગોઠવો',
      'sec_preferences': 'પસંદગીઓ',
      'sec_support': 'સપોર્ટ અને શેર',
      'sec_legal': 'કાનૂની અને નીતિઓ',
      'sec_about': 'એપ્લિકેશન વિશે',
      'settings_language': 'એપ્લિકેશન ભાષા',
      'settings_theme': 'ડિસ્પ્લે થીમ',
      'settings_font_size': 'વાંચન અક્ષર કદ',
      'setting_share_app': 'એપ્લિકેશન શેર કરો',
      'setting_share_subtitle': 'મિત્રો અને પરિવાર સાથે શ્રી રામકથા શેર કરો',
      'setting_rate_app': 'એપ્લિકેશનને રેટ કરો',
      'setting_rate_subtitle': 'પ્લે સ્ટોર પર તમારો મૂલ્યવાન રેટિંગ અને પ્રતિસાદ આપો',
      'settings_about': 'અમારા વિશે',
      'settings_about_app': 'વાલ્મીકિ રામાયણ વિશે',
      'settings_about_subtitle': 'એપ્લિકેશન વિગતો, આવૃત્તિ અને માહિતી',
      'settings_privacy': 'ગોપનીયતા નીતિ',
      'settings_terms': 'નિયમો અને શરતો',
      'settings_version': 'એપ્લિકેશન આવૃત્તિ',
      'developer_name': 'વાલ્મીકિ રામાયણ ભક્તિ ટીમ',
      'copyright_text': '© 2026 વાલ્મીકિ રામાયણ. સર્વાધિકાર સુરક્ષિત.',
      'coming_soon_title': 'ટૂંક સમયમાં આવી રહ્યું છે',
      'coming_soon_desc':
      'આ ભાષા માટે ડેટા ઉપલબ્ધ થઈ રહ્યો છે. કૃપા કરીને ભાષા બદલો અથવા પાછળથી પ્રયાસ કરો.',
      'change_language': 'ભાષા બદલો',
      'error_loading_title': 'સામગ્રી લોડ થઈ શકી નથી',
      'error_loading_desc':
      'કૃપા કરીને તમારું ઇન્ટરનેટ કનેક્શન ચકાસો અને ફરી પ્રયાસ કરો.',
      'retry_btn': 'ફરી પ્રયાસ કરો',
      'read_more': 'વધુ વાંચો',
      'items_count': 'આઇટમ્સ',
      'share_text': 'વાલ્મીકિ રામાયણ એપ્લિકેશનમાંથી',
      'link_copied': 'લિંક નકલ કરી',
      'theme_light': 'લાઇટ (પ્રકાશ)',
      'theme_dark': 'ડાર્ક (અંધકાર)',
      'theme_system': 'સિસ્ટમ',
      'about_description':
      'વાલ્મીકિ રામાયણ એ ભગવાન શ્રી રામચંદ્રજીના પાવન ચરિત્ર, આદર્શો અને સનાતન જ્ઞાનને ડિજિટલ સ્વરૂપે સરળતાથી વાંચવા માટેની એક ભક્તિમય એપ્લિકેશન છે.',
      'cat_sath_kand': 'સાત કાંડ',
      'cat_rishio': 'ઋષિઓ',
      'cat_vanaro': 'વાનરો',
      'cat_rakshaso': 'રાક્ષસો',
      'cat_anya_patrono': 'અન્ય પાત્રો',
      'cat_mukhya_sthalo': 'મુખ્ય સ્થળો',
      'cat_temples': 'મંદિરો',
      'cat_divya_astro': 'દિવ્ય અસ્ત્રો',
      'nav_status': 'સ્ટેટસ',
      'status_empty_title': 'કોઈ સ્ટેટસ ઉપલબ્ધ નથી',
      'status_empty_desc': 'હાલમાં કોઈ ભક્તિ સ્ટેટસ ઉપલબ્ધ નથી. કૃપા કરીને ફરી પ્રયાસ કરો.',
      'status_category_empty_title': 'આ કેટેગરીમાં સ્ટેટસ નથી',
      'status_category_empty_desc': 'આ કેટેગરીમાં હાલમાં કોઈ સ્ટેટસ ઉપલબ્ધ નથી.',
      'status_attribution': 'વાલ્મીકિ રામાયણ',
      'daily_quote_label': 'આજનો વિચાર',
      'daily_quote_unavailable': 'આજનો વિચાર હાલમાં ઉપલબ્ધ નથી.',
      'share': 'શેર કરો',
      'ad_unlock_story_title': 'કથા અનલૉક કરો',
      'ad_unlock_story_desc': 'આ કથા વાંચવા માટે એક નાની જાહેરાત જુઓ.',
      'ad_unlock_status_title': 'સ્ટેટસ શેર અનલૉક કરો',
      'ad_unlock_status_desc': 'આ દિવ્ય સ્ટેટસ શેર કરવા માટે એક નાની જાહેરાત જુઓ.',
      'ad_watch_btn': 'જાહેરાત જુઓ',
      'ad_maybe_later_btn': 'પછીથી',
      'ad_not_available': 'જાહેરાત ઉપલબ્ધ નથી, કૃપા કરીને ફરી પ્રયાસ કરો.',
    },
    'hi': {
      'app_title': 'वाल्मीकि रामायण',
      'app_subtitle': 'श्री राम के पावन जीवन और आदर्शों की यात्रा',
      'hero_subtitle': 'रामायण के पवित्र ज्ञान और पात्रों की सुंदर यात्रा',
      'select_language_title': 'वाल्मीकि रामायण',
      'select_language_subtitle': 'श्री राम के पावन जीवन और आदर्शों की यात्रा',
      'choose_language_prompt': 'अपनी भाषा चुनें',
      'continue_btn': 'आगे बढ़ें',
      'nav_home': 'मुख्य पृष्ठ',
      'nav_categories': 'श्रेणियाँ',
      'nav_favorites': 'पसंदीदा',
      'nav_settings': 'सेटिंग्स',
      'main_categories_header': 'मुख्य श्रेणियाँ',
      'continue_reading': 'पढ़ना जारी रखें',
      'recently_viewed': 'हाल ही में देखा गया',
      'favorites_preview': 'आपकी पसंदीदा सामग्री',
      'search_placeholder': 'खोजें (शीर्षक या विवरण)...',
      'category_search_placeholder': 'श्रेणी में खोजें...',
      'no_results_title': 'कोई परिणाम नहीं मिला',
      'no_results_desc': 'आपके खोज शब्द से मेल खाने वाली कोई सामग्री नहीं मिली।',
      'no_favorites_title': 'कोई पसंदीदा नहीं जोड़ा गया',
      'no_favorites_desc': 'आपने अभी तक कोई पसंदीदा आइटम नहीं जोड़ा है।',
      'coming_soon_title': 'शीघ्र आ रहा है',
      'coming_soon_desc':
      'इस भाषा की सामग्री जल्द उपलब्ध होगी। कृपया भाषा बदलें या बाद में प्रयास करें।',
      'change_language': 'भाषा बदलें',
      'error_loading_title': 'सामग्री लोड नहीं हो सकी',
      'error_loading_desc':
      'कृपया अपना इंटरनेट कनेक्शन जांचें और पुनः प्रयास करें।',
      'retry_btn': 'पुनः प्रयास करें',
      'read_more': 'और पढ़ें',
      'items_count': 'सामग्री',
      'share_text': 'वाल्मीकि रामायण ऐप से',
      'link_copied': 'लिंक कॉपी किया गया',
      'theme_light': 'लाइट (प्रकाश)',
      'theme_dark': 'डार्क (अंधकार)',
      'theme_system': 'सिस्टम',
      'font_small': 'छोटा',
      'font_medium': 'मध्यम',
      'font_large': 'बड़ा',
      'font_extra_large': 'अति बड़ा',
      'settings_title': 'सेटिंग्स',
      'settings_header_subtitle': 'अपने भक्ति अनुभव को निजीकृत करें',
      'sec_preferences': 'पसंद',
      'sec_support': 'सहायता एवं साझा करें',
      'sec_legal': 'कानूनी एवं नीतियाँ',
      'sec_about': 'ऐप के बारे में',
      'settings_language': 'ऐप भाषा',
      'settings_theme': 'थीम',
      'settings_font_size': 'अक्षर का आकार',
      'setting_share_app': 'ऐप शेयर करें',
      'setting_share_subtitle': 'मित्रों और परिवार के साथ श्री रामकथा साझा करें',
      'setting_rate_app': 'ऐप को रेट करें',
      'setting_rate_subtitle': 'प्ले स्टोर पर अपनी बहुमूल्य रेटिंग दें',
      'settings_about': 'हमारे बारे में',
      'settings_about_app': 'वाल्मीकि रामायण के बारे में',
      'settings_about_subtitle': 'ऐप संस्करण और जानकारी',
      'settings_privacy': 'गोपनीयता नीति',
      'settings_terms': 'नियम एवं शर्तें',
      'settings_version': 'ऐप संस्करण',
      'developer_name': 'वाल्मीकि रामायण भक्ति टीम',
      'copyright_text': '© 2026 वाल्मीकि रामायण। सर्वाधिकार सुरक्षित।',
      'about_description':
      'वाल्मीकि रामायण भगवान श्री रामचंद्र के पावन चरित्र, आदर्शों और सनातन ज्ञान को समर्पित एक भक्तिपूर्ण ऐप है.',
      'cat_sath_kand': 'सात कांड',
      'cat_rishio': 'ऋषि मुनि',
      'cat_vanaro': 'वानर',
      'cat_rakshaso': 'राक्षस',
      'cat_anya_patrono': 'अन्य पात्र',
      'cat_mukhya_sthalo': 'मुख्य स्थल',
      'cat_temples': 'मंदिर',
      'cat_divya_astro': 'दिव्य अस्त्र',
      'nav_status': 'स्टेटस',
      'status_empty_title': 'कोई स्टेटस उपलब्ध नहीं',
      'status_empty_desc': 'अभी कोई भक्ति स्टेटस उपलब्ध नहीं है। कृपया पुनः प्रयास करें।',
      'status_category_empty_title': 'इस श्रेणी में स्टेटस नहीं है',
      'status_category_empty_desc': 'इस श्रेणी में अभी कोई स्टेटस उपलब्ध नहीं है।',
      'status_attribution': 'वाल्मीकि रामायण',
      'daily_quote_label': 'आज का विचार',
      'daily_quote_unavailable': 'आज का विचार अभी उपलब्ध नहीं है।',
      'share': 'शेयर करें',
      'ad_unlock_story_title': 'कथा अनलॉक करें',
      'ad_unlock_story_desc': 'इस कथा को पढ़ने के लिए एक छोटा विज्ञापन देखें।',
      'ad_unlock_status_title': 'स्टेटस शेयर अनलॉक करें',
      'ad_unlock_status_desc': 'इस दिव्य स्टेटस को शेयर करने के लिए एक छोटा विज्ञापन देखें।',
      'ad_watch_btn': 'विज्ञापन देखें',
      'ad_maybe_later_btn': 'बाद में',
      'ad_not_available': 'विज्ञापन उपलब्ध नहीं है, कृपया पुनः प्रयास करें।',
    },
    'en': {
      'app_title': 'Valmiki Ramayan',
      'app_subtitle':
      'A Sacred Journey into the Life & Ideals of Lord Shri Ram',
      'hero_subtitle':
      'Explore the divine knowledge, sacred places, and revered characters of Ramayana',
      'select_language_title': 'Valmiki Ramayan',
      'select_language_subtitle':
      'A Sacred Journey into the Life & Ideals of Lord Shri Ram',
      'choose_language_prompt': 'Select Your Language',
      'continue_btn': 'Continue',
      'nav_home': 'Home',
      'nav_categories': 'Categories',
      'nav_favorites': 'Favorites',
      'nav_settings': 'Settings',
      'main_categories_header': 'Main Categories',
      'continue_reading': 'Continue Reading',
      'recently_viewed': 'Recently Viewed',
      'favorites_preview': 'Your Favorites',
      'search_placeholder': 'Search title or description...',
      'category_search_placeholder': 'Search in category...',
      'no_results_title': 'No Results Found',
      'no_results_desc': 'We couldn\'t find any match for your search term.',
      'no_favorites_title': 'No Favorites Saved',
      'no_favorites_desc': 'Items you bookmark will appear here.',
      'coming_soon_title': 'Coming Soon',
      'coming_soon_desc':
      'Data for this language is being prepared. Please switch to Gujarati or check back soon.',
      'change_language': 'Change Language',
      'error_loading_title': 'Unable to Load Content',
      'error_loading_desc':
      'Please check your internet connection and try again.',
      'retry_btn': 'Retry',
      'read_more': 'Read More',
      'items_count': 'items',
      'share_text': 'Shared from Valmiki Ramayan App',
      'link_copied': 'Link copied to clipboard',
      'theme_light': 'Light Mode',
      'theme_dark': 'Spiritual Dark Mode',
      'theme_system': 'System Default',
      'font_small': 'Small',
      'font_medium': 'Medium',
      'font_large': 'Large',
      'settings_title': 'Settings',
      'settings_language': 'App Language',
      'settings_theme': 'App Theme',
      'settings_font_size': 'Reading Font Size',

      'setting_share_app': 'Share App',
      'setting_share_subtitle': 'Share the divine Ramayana with friends and family',
      'setting_rate_app': 'Rate App',
      'setting_rate_subtitle': 'Give your valuable rating and feedback on Play Store',

      'sec_support': 'Support & Share',
      'sec_legal': 'Legal & Policies',

      'settings_about': 'About Valmiki Ramayan',
      'settings_privacy': 'Privacy Policy',
      'settings_terms': 'Terms & Condition',
      'settings_version': 'App Version',
      'about_description':
      'Valmiki Ramayan is a spiritual application dedicated to presenting the sublime life, eternal virtues, and divine teachings of Lord Shri Ram.',
      'cat_sath_kand': 'Seven Kandas',
      'cat_rishio': 'Rishis & Sages',
      'cat_vanaro': 'Vanaras',
      'cat_rakshaso': 'Rakshasas',
      'cat_anya_patrono': 'Other Characters',
      'cat_mukhya_sthalo': 'Sacred Places',
      'cat_temples': 'Temples',
      'cat_divya_astro': 'Divine Weapons',
      'nav_status': 'Status',
      'status_empty_title': 'No Statuses Available',
      'status_empty_desc': 'No devotional statuses are available right now. Please try again later.',
      'status_category_empty_title': 'No Status in This Category',
      'status_category_empty_desc': 'No statuses are available in this category right now.',
      'status_attribution': 'Valmiki Ramayan',
      'daily_quote_label': 'Daily Thought',
      'daily_quote_unavailable': 'Daily quote is not available right now.',
      'share': 'Share',
      'ad_unlock_story_title': 'Unlock Story',
      'ad_unlock_story_desc': 'Watch a short ad to unlock and read this story.',
      'ad_unlock_status_title': 'Unlock Status Sharing',
      'ad_unlock_status_desc': 'Watch a short ad to continue sharing this divine status.',
      'ad_watch_btn': 'Watch Ads',
      'ad_maybe_later_btn': 'Maybe Later',
      'ad_not_available': 'Ad not available, please try again.',
    },
  };

  static String get(String key, String langCode) {
    final langMap = _strings[langCode] ?? _strings['gu']!;
    return langMap[key] ?? _strings['en']?[key] ?? key;
  }
}